### ISSUE TITLE
banned on open proxy

### ISSUE THREAD

**Issue by Awan** [hashbang/hashbang.sh#151] opened 2021-02-05 10:27 UTC
http://dronebl.org/lookup?ip=2a01:4f8:141:1272::2

freenode has banned my shell.

**Comment by Shinoa-Fores** [comment] 2022-12-15 02:17
I've noticed in past week can't even connect service bots from hashbang to *any* irc server I've tried.

**Comment by KellerFuchs** [comment] 2023-04-19 15:22
Presumably caused by a user running an open proxy under their account.  The issue seems gone now, so I can't investigate further  :/

A long-term fix would be to give each user a separate IPv6 address and not let them listen on the server's public-facing IPv4 address.  IIRC I suggested that before my break from the project, but it's a bit more than out of scope for this issue  ^^'

**Closed as completed by KellerFuchs** 2023-04-19 15:22 UTC
